### ISSUE TITLE
Color selection for HTML/CSS dropdown visibility

### ISSUE THREAD

**Issue by JaellyBean** [AchroDev/koffee-kreme#1]
![Screenshot 2024-04-21 213850](https://github.com/AchroDev/koffee-kreme/assets/145577640/2029eb58-3e22-46ff-890c-7404b37c295b)
![Screenshot 2024-04-21 213954](https://github.com/AchroDev/koffee-kreme/assets/145577640/b8f78fc1-1e75-4d73-8eda-b29ec92c7907)

When entering in "<" to bring up the selector, the grey color on the options is extremely hard to read. As well as when typing out properties in CSS, the options are hard to read.

**Comment by AchroDev** [comment]
Thanks for taking the time to submit your issue. It looks like the text is just a tad bit too light. I'm taking a look at some similar, but better contrasting colors to use and will apply the fix when it's ready.

**Comment by AchroDev** [comment]
@JaellyBean I have made some changes to the theme overall and included the suggestion box as part of the update. Please let me know if the changes have helped, not changed anything, or made it worse for you.

**Comment by JaellyBean** [comment]
I appreciate the work put into the theme, its clearer now in the menu, and I would think a slightly darker background would contrast the "<". Either way much better now, thank you!

**Comment by AchroDev** [comment]
Glad to hear the issue has been solved, and it's much clearer to see. If you have any other issues, please be sure to create another one!
